image:
  repository: selcpacr.azurecr.io/uservicepartymanagement
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.1.11 # TODO remove MAIN_AUDIENCE from env section of deployment when upgrading to version equal or greater than 0.1.12

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  APPLICATIONINSIGHTS_INSTRUMENTATION_JDBC_ENABLED: 'false' # TODO: put me true after PROD have some data: this instrumentation will go in conflict with the application when the db is empty, turn it on (true) only after db population
  REQUIRED_CONTACT_POINT_NR: "1"
